### ISSUE TITLE
Error: Cannot find wait timer

### ISSUE THREAD

**Issue by jacques** [npm/npm-fullfat-registry#1]
```
<- garret-0.0.3-master-c419b8d.tgz
PUT garret
ERROR [Error: Cannot find wait timer]

Error: Cannot find wait timer
    at Feed.got_activity (/home/ubuntu/node_modules/npm-fullfat-registry/node_modules/follow/lib/feed.js:355:21)
    at Feed.on_couch_data (/home/ubuntu/node_modules/npm-fullfat-registry/node_modules/follow/lib/feed.js:412:8)
    at Changes.handle_confirmed_req_event (/home/ubuntu/node_modules/npm-fullfat-registry/node_modules/follow/lib/feed.js:308:30)
    at Changes.EventEmitter.emit (events.js:95:17)
    at Changes.emit_changes (/home/ubuntu/node_modules/npm-fullfat-registry/node_modules/follow/lib/stream.js:223:12)
    at Changes.resume (/home/ubuntu/node_modules/npm-fullfat-registry/node_modules/follow/lib/stream.js:107:8)
    at Feed.resume (/home/ubuntu/node_modules/npm-fullfat-registry/node_modules/follow/lib/feed.js:388:26)
    at FullFat.resume (/home/ubuntu/node_modules/npm-fullfat-registry/fullfat.js:664:17)
    at FullFat.onputres (/home/ubuntu/node_modules/npm-fullfat-registry/fullfat.js:510:10)
    at f (/home/ubuntu/node_modules/npm-fullfat-registry/node_modules/once/once.js:16:25)
```

**Comment by scandinave** [comment]
I'm facing the same problem. I know this repository are quite old but it's the only solution i have found to save a repository for offline use. Maybe you can tell me another way to achieve that? I need complete backup that work inside intranet without internet access
