### ISSUE TITLE
Sync at sequence 13570 aborts with error

### ISSUE THREAD

**Issue by sjanecki** [npm/npm-fullfat-registry#10]
I'm syncing from SkimDB to my local couchdb.
Application at sequence 13570 quits.

After restarting at sequence 13570 I've got something like this:

```
START npm FullFat/1.1.4 node/v0.10.9 pid=20272
13571: derby-auth
-> derby-auth-0.0.6.tgz
<- derby-auth-0.0.6.tgz
ERROR { [Error: {"error":"unknown_error","reason":"function_clause"}
] statusCode: 500 }

Error: {"error":"unknown_error","reason":"function_clause"}

    at IncomingMessage.<anonymous> (/opt/scripts/node_modules/npm-fullfat-registry/node_modules/parse-json-response/parse.js:38:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:415:13)
```

**Comment by terinjokes** [comment]
The npm couchapp requires CouchDB 1.4.0 or greater, though 1.5.0 is recommended. I run CouchDB 1.6.1 and have not had these problems.
